[build]
  base = "frontend"
  command = "npm install && node node_modules/vite/bin/vite.js build"
  publish = "dist"

[build.environment]
  NODE_VERSION = "18"
  NPM_CONFIG_PRODUCTION = "false"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
